import HeaderBar from "../components/HeaderBar";
import HeaderLogo from "../components/HeaderLogo";
import { AccessButton, ConfirmAccessButton } from "../components/AccessButton";
import CartButton from "../components/CartButton";
import OrderButton from "../components/OrderButton";
import { Grid, Typography, TextField } from "@material-ui/core";
import styles from "../styles/Access.module.css";
import Head from "next/head";

export default function RestrictedAccess() {
  return (
    <div>
      <Head>
        <title>Bee Veggie - Cozinha Vegetariana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container justifyContent="flex-end">
        <Grid item>
          <AccessButton />
        </Grid>
      </Grid>

      <Grid container justifyContent="center">
        <Grid item>
          <HeaderLogo />
        </Grid>
      </Grid>

      <HeaderBar
        title={<Typography variant="h4">Acesso Restrito</Typography>}
        icon1={<OrderButton />}
        icon2={<CartButton />}
      />

      <main className={styles.main}>
        <Grid container direction="column" alignItems="center" spacing={2}>
          <Grid item>
            <Typography variant="h6" className={styles.spanBold}>
              Se você trabalha na cozinha insira seu e-mail para entrar no
              acesso restrito
            </Typography>
          </Grid>
          <Grid item>
            <div className={styles.textField}>
              <TextField
                label="E-mail"
                classes={{
                  root: styles.inputRoot,
                  input: styles.inputInput,
                }}
                type="email"
                helperText='Insira o e-mail: worker@beeveggie.com'
              />
            </div>
          </Grid>
          <Grid item>
            <ConfirmAccessButton />
          </Grid>
        </Grid>
      </main>
    </div>
  );
}
