import React from "react";
import HeaderBar from "../components/HeaderBar";
import HeaderLogo from "../components/HeaderLogo";
import AccessButton from "../components/AccessButton";
import CartButton from "../components/CartButton";
import OrderButton from "../components/OrderButton";
import { Grid, Typography, TextField, Chip, Divider } from "@material-ui/core";
import styles from "../styles/Cart.module.css";
import FaceIcon from "@material-ui/icons/Face";
import RestaurantIcon from "@material-ui/icons/Restaurant";
import FastfoodIcon from "@material-ui/icons/Fastfood";
import CancelIcon from "@material-ui/icons/Cancel";
import LocalAtmIcon from "@material-ui/icons/LocalAtm";
import CreditCardIcon from "@material-ui/icons/CreditCard";

export default function Cart() {
  const [name, setName] = React.useState("");
  const [table, setTable] = React.useState("");

  return (
    <div>
      <Head>
        <title>Bee Veggie - Cozinha Vegetariana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Grid container justifyContent="flex-end">
        <Grid item>
          <AccessButton />
        </Grid>
      </Grid>

      <Grid container justifyContent="center">
        <Grid item>
          <HeaderLogo />
        </Grid>
      </Grid>

      <HeaderBar
        title={<Typography variant="h4">Pedidos</Typography>}
        icon1={<OrderButton />}
        icon2={<CartButton />}
      />

      <main>
        <Grid container direction="column" alignItems="center" spacing={2}>
          <Grid item>
            <Typography variant="h6">Insira suas informações</Typography>
          </Grid>
          <Grid item>
            <div className={styles.search}>
              <TextField
                label="Nome"
                classes={{
                  root: styles.inputRoot,
                  input: styles.inputInput,
                }}
                onChange={(e) => setName(e.target.value)}
              />
            </div>
          </Grid>
          <Grid item>
            <div className={styles.search}>
              <TextField
                label="Mesa"
                classes={{
                  root: styles.inputRoot,
                  input: styles.inputInput,
                }}
                type="number"
                onChange={(e) => setTable(e.target.value)}
              />
            </div>
          </Grid>
          <Grid item>
            <Chip icon={<FaceIcon />} label={name} variant="outlined" />

            <Chip icon={<RestaurantIcon />} label={table} variant="outlined" />
          </Grid>
          <Grid item>
            <Typography variant="h6">Confirme seu pedido</Typography>
          </Grid>
          <Grid item>
            <FastfoodIcon />
            <Typography variant="p">Exemplo title</Typography>
            <CancelIcon />
            <br />
            <Typography variant="p">R$00</Typography>
          </Grid>
          <Grid item>
            <Typography variant="h6">Forma de Pagamento</Typography>
          </Grid>
          <Grid item>
            <img src="images/money.svg" />
            <Typography variant="p">Dinheiro</Typography>
            <img src="images/credit.svg" />
            <Typography variant="p">Crédito/Débito</Typography>
            <img src="images/paypal.svg" />
            <Typography variant="p">Paypal</Typography>
          </Grid>
        </Grid>
        <Divider />
      </main>
    </div>
  );
}
