import React from "react";
import HeaderBar from "../components/HeaderBar";
import HeaderLogo from "../components/HeaderLogo";
import AccessButton from "../components/AccessButton";
import CartButton from "../components/CartButton";
import OrderButton from "../components/OrderButton";
import MoneyButton from "../components/MoneyButton";
import CreditButton from "../components/CreditButton";
import PaypalButton from "../components/PaypalButton";
import ConfirmOrderButton from "../components/ConfirmOrderButton";
import {
  Grid,
  Typography,
  TextField,
  Chip,
  Divider,
  IconButton,
} from "@material-ui/core";
import styles from "../styles/Cart.module.css";
import FaceIcon from "@material-ui/icons/Face";
import RestaurantIcon from "@material-ui/icons/Restaurant";
import FastfoodIcon from "@material-ui/icons/Fastfood";
import CancelIcon from "@material-ui/icons/Cancel";
import Head from "next/head";

export default function Cart() {
  const [name, setName] = React.useState("");
  const [table, setTable] = React.useState("");
  const [moneyClick, setMoneyClick] = React.useState(false);
  const [money, setMoney] = React.useState("");
  const [payment, setPayment] = React.useState('');

  const moneyClickHandler = () => {
    setMoneyClick(true);
    setPayment('Dinheiro')
  };

  const creditClickHandler = () => {
    setMoneyClick(false);
    setPayment('Crédito/Débito')
  };

  const paypalClickHandler = () => {
    setMoneyClick(false);
    setPayment('Paypal')
  };

  return (
    <div>
      <Head>
        <title>Bee Veggie - Cozinha Vegetariana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container justifyContent="flex-end">
        <Grid item>
          <AccessButton />
        </Grid>
      </Grid>

      <Grid container justifyContent="center">
        <Grid item>
          <HeaderLogo />
        </Grid>
      </Grid>

      <HeaderBar
        title={<Typography variant="h4">Pedidos</Typography>}
        icon1={<OrderButton />}
        icon2={<CartButton />}
      />

      <main className={styles.main}>
        <Grid container direction="column" alignItems="center" spacing={2}>
          <Grid item>
            <Typography variant="h6">Insira suas informações</Typography>
          </Grid>
          <Grid item>
            <div className={styles.textField}>
              <TextField
                label="Nome"
                classes={{
                  root: styles.inputRoot,
                  input: styles.inputInput,
                }}
                onChange={(e) => setName(e.target.value)}
              />
            </div>
          </Grid>
          <Grid item>
            <div className={styles.textField}>
              <TextField
                label="Mesa"
                classes={{
                  root: styles.inputRoot,
                  input: styles.inputInput,
                }}
                type="number"
                onChange={(e) => setTable(e.target.value)}
              />
            </div>
          </Grid>
          <Grid item>
            <Chip
              icon={<FaceIcon />}
              label={name}
              variant="outlined"
              className={styles.chip}
            />
            <Chip
              icon={<RestaurantIcon />}
              label={table}
              variant="outlined"
              className={styles.chip}
            />
          </Grid>
        </Grid>

        <Divider />

        <Grid container direction="column" alignItems="center" spacing={2}>
          <Grid item>
            <Typography variant="h6">Confirme seu pedido</Typography>
          </Grid>
          <Grid item>
            <FastfoodIcon />
            <Typography variant="p" className={styles.spanBold}>
              {" "}
              Exemplo title{" "}
            </Typography>
            <Typography variant="p"> R$00 </Typography>
            <CancelIcon />
          </Grid>
        </Grid>

        <Divider />

        <Grid container direction="column" alignItems="center" spacing={2}>
          <Grid item>
            <Typography variant="h6">Forma de Pagamento</Typography>
          </Grid>
          <Grid item>
            <IconButton>
              <MoneyButton onClick={moneyClickHandler} />
            </IconButton>
            <IconButton>
              <CreditButton onClick={creditClickHandler}/>
            </IconButton>
            <IconButton>
              <PaypalButton onClick={paypalClickHandler}/>
            </IconButton>
          </Grid>
        </Grid>

        <Divider />
        <Grid container justifyContent="center" spacing={3}>
          <Grid item>
            {moneyClick == true ? (
              <div className={styles.textField}>
                <TextField
                  label="Valor em dinheiro"
                  classes={{
                    root: styles.inputRoot,
                    input: styles.inputInput,
                  }}
                  type="number"
                  onChange={(e) => setMoney(e.target.value)}
                />
              </div>
            ) : (
              <div className={styles.textField}>
                <TextField
                  label="Valor em dinheiro"
                  classes={{
                    root: styles.inputRoot,
                    input: styles.inputInput,
                  }}
                  type="number"
                  onChange={(e) => setMoney(e.target.value)}
                  disabled
                />
              </div>
            )}
          </Grid>
        </Grid>

        <Grid container justifyContent="center" spacing={3}>
          <Grid item className={styles.spanBold}>
          <Typography variant="p">Forma de Pagamento</Typography>
          <br />
            <Typography variant="p">Total</Typography>
            <br />
            <Typography variant="p">Dinheiro</Typography>
            <br />
            <Typography variant="p">Troco</Typography>
          </Grid>
          <Grid item>
          <Typography variant="p">{payment}</Typography>
            <br />
            <Typography variant="p">R$00</Typography>
            <br />
            {money == "" ? (
              <Typography variant="p">R$00</Typography>
            ) : (
              <Typography variant="p">R${money}</Typography>
            )}
            <br />
            <Typography variant="p">R$00</Typography>
          </Grid>
        </Grid>

        <Divider />

        <Grid container direction="column" alignItems="center" spacing={2}>
          <Grid item>
            <ConfirmOrderButton />
          </Grid>
        </Grid>
      </main>
    </div>
  );
}
